# Generated by Django 4.2.16 on 2024-09-12 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Введите номер телефона', max_length=35, null=True, verbose_name='Телефон')),
                ('FIO', models.CharField(help_text='Введите свои Фамилию, Имя и Отчество', max_length=100, verbose_name='Ф.И.О.')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('FIO',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.CharField(default=django.utils.timezone.now, verbose_name='Дата и время последней рассылки')),
                ('status_attempt', models.CharField(choices=[('success', 'успешно'), ('failure ', 'не успешно')], max_length=40, verbose_name='Статус рассылки')),
                ('report', models.CharField(max_length=40, verbose_name='Ответ почтового сервера, если он был')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ('last_attempt',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Укажите тему письма', max_length=40, verbose_name='Тема письма')),
                ('text', models.CharField(max_length=150, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('topic',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой рассылки')),
                ('intervals', models.CharField(choices=[('dayly', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=40, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in process', 'Запущена'), ('finished', 'Завершена')], max_length=40, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('status',),
            },
        ),
    ]
