# Generated by Django 4.2.16 on 2024-09-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='clients',
            field=models.ManyToManyField(related_name='subscription', to='client.client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='client.messages', verbose_name='сообщение'),
        ),
    ]
