# Generated by Django 4.2.16 on 2024-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_phone_alter_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='intervals',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=40, verbose_name='Периодичность'),
        ),
    ]
